---

- name: Update the cache...
  apt: update_cache=yes

- name: Install Tomcat
  apt: name={{ item }} state=present
  with_items:
      - tomcat7
      - git
      - curl
  notify:
    - start tomcat service

- name: Code clone
  git:
    repo: "{{ git_url }}"
    dest: "{{ dest_path }}"

- name: Copy sample war file
  copy:
    src: "{{ dest_path }}/{{ war_file_path }}"
    dest: "{{ wepapps_path }}"
    remote_src: yes
  notify:
    - restart tomcat service


